Ensure abstractions/tor AppArmor file always exists

diff --git a/debian/anon-ws-disable-stacked-tor.postinst b/debian/anon-ws-disable-stacked-tor.postinst
--- a/debian/anon-ws-disable-stacked-tor.postinst
+++ b/debian/anon-ws-disable-stacked-tor.postinst
@@ -40,6 +40,12 @@ configure_function() {
    adduser --quiet user debian-tor
 
 #### meta end
+
+   ## Ensure a Tor AppArmor include file always exists, so that AppArmor
+   ## doesn't fail to load because Tor isn't installed.
+   if ! [ -f /etc/apparmor.d/abstractions/tor ]; then
+      touch /etc/apparmor.d/abstractions/tor
+   fi
 }
 
 case "$1" in
